export default {
	GET_PATIENTS: 'GET_PATIENTS',
	SET_PATIENTS: 'SET_PATIENTS',
	ADD_PATIENT: 'ADD_PATIENT',
	UPDATE_PATIENT: 'UPDATE_PATIENT',
	DELETE_PATIENT: 'DELETE_PATIENT',
	SET_ALERT: 'SET_ALERT',
	RESET_ALERT: 'RESET_ALERT',
};